/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersSlugRouteImport } from './routes/players/$slug'
import { Route as LeaguesSlugRouteImport } from './routes/leagues/$slug'
import { Route as ExplorePlayersRouteImport } from './routes/explore/players'
import { Route as ExploreTypeSlugRouteImport } from './routes/explore/$type/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersSlugRoute = PlayersSlugRouteImport.update({
  id: '/players/$slug',
  path: '/players/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesSlugRoute = LeaguesSlugRouteImport.update({
  id: '/leagues/$slug',
  path: '/leagues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorePlayersRoute = ExplorePlayersRouteImport.update({
  id: '/explore/players',
  path: '/explore/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTypeSlugRoute = ExploreTypeSlugRouteImport.update({
  id: '/explore/$type/$slug',
  path: '/explore/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/explore/players': typeof ExplorePlayersRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/explore/$type/$slug': typeof ExploreTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/explore/players': typeof ExplorePlayersRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/explore/$type/$slug': typeof ExploreTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/explore/players': typeof ExplorePlayersRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/explore/$type/$slug': typeof ExploreTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/explore/players'
    | '/leagues/$slug'
    | '/players/$slug'
    | '/explore/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/explore/players'
    | '/leagues/$slug'
    | '/players/$slug'
    | '/explore/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/explore/players'
    | '/leagues/$slug'
    | '/players/$slug'
    | '/explore/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorePlayersRoute: typeof ExplorePlayersRoute
  LeaguesSlugRoute: typeof LeaguesSlugRoute
  PlayersSlugRoute: typeof PlayersSlugRoute
  ExploreTypeSlugRoute: typeof ExploreTypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$slug': {
      id: '/players/$slug'
      path: '/players/$slug'
      fullPath: '/players/$slug'
      preLoaderRoute: typeof PlayersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$slug': {
      id: '/leagues/$slug'
      path: '/leagues/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof LeaguesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/players': {
      id: '/explore/players'
      path: '/explore/players'
      fullPath: '/explore/players'
      preLoaderRoute: typeof ExplorePlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$type/$slug': {
      id: '/explore/$type/$slug'
      path: '/explore/$type/$slug'
      fullPath: '/explore/$type/$slug'
      preLoaderRoute: typeof ExploreTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ExplorePlayersRoute: ExplorePlayersRoute,
  LeaguesSlugRoute: LeaguesSlugRoute,
  PlayersSlugRoute: PlayersSlugRoute,
  ExploreTypeSlugRoute: ExploreTypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

